[package]
name = "smartlights"
version = "0.1.0"
authors = ["Tiziano Santoro <tiziano88@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
params = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.5"
maplit = "0.1"
rgb = "0.7.0"
mote = { git = "https://github.com/tiziano88/mote-rs" }
unicase = "*"
