#!/bin/sh

set -x
set -e

#readonly TARGET='arm-unknown-linux-gnueabihf'
readonly TARGET='arm-unknown-linux-gnueabi'

readonly REMOTE='pi@192.168.0.21'

cargo build --target=${TARGET}
scp target/${TARGET}/debug/smartlights ${REMOTE}:/home/pi/
#ssh ${TARGET} RUST_BACKTRACE=1 /home/pi/smartlights
