#!/bin/sh

set -x
set -e

#readonly TARGET='arm-unknown-linux-gnueabihf'
readonly TARGET='arm-unknown-linux-gnueabi'

readonly REMOTE='pi@0.tcp.eu.ngrok.io'
readonly PORT='18107'

cargo build --release --target=${TARGET}
scp -P ${PORT} target/${TARGET}/release/smartlights ${REMOTE}:/home/pi/
#ssh ${TARGET} RUST_BACKTRACE=1 /home/pi/smartlights
